name: GitHub Actions Demo

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github
      
  pull_request:
    branches: 
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.event_name }}"
          echo "${{ github.ref }}"

      - uses: actions/checkout@v3.3.0

      - name: ls
        run: |
          echo ${{ github.repository }}"
          ls -lha
          
