name: Hello World Docker CI

on:
  push:
    paths: hello-world-docker-action/*
  workflow_dispatch:
    
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
    
      - name: Test container action
        id: hello
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@rf-santos'
        
      - name: Output time
        run: echo "${{ steps.hello.outputs.time }}"
